#!/bin/bash

set -e

IFLINK="$1"
NMMODE="$2"


ddns_stop() {
	systemctl --no-block stop hetzner-ddns.service
}
ddns_start() {
	systemctl --no-block start hetzner-ddns.service
}


case "${NMMODE}" in
"vpn-up")
	echo "ddns_stop: vpn=${IFLINK} went up"
	ddns_stop
;;
"vpn-down")
	echo "ddns_start: vpn=${IFLINK} went down"
	ddns_start
;;
esac

exit 0
