#!/usr/bin/env bash

PREFIX_LEN='64'

set-sysctl() {
	# remove old temp addresses quicker
	sysctl -w net.ipv6.conf."${IFLINK}".temp_prefered_lft=43210 >/dev/null
	sysctl -w net.ipv6.conf."${IFLINK}".temp_valid_lft=87654 >/dev/null

	# force usage of temporary address
	sysctl -w net.ipv6.conf."${IFLINK}".addr_gen_mode=3 >/dev/null
	sysctl -w net.ipv6.conf."${IFLINK}".use_tempaddr=2 >/dev/null
}

set-ipv6-token() {
	# enable router advertisement on LAN network adapter
	# https://unix.stackexchange.com/questions/61641/how-can-i-disable-automatic-ipv6-neighbor-route-advertisement-on-a-router
	sysctl -w net.ipv6.conf."${IFLINK}".accept_ra=2 >/dev/null
	sleep 1s
	ip token set "::${MY_IPV6_SUFFIX}/${PREFIX_LEN}" dev "${IFLINK}"
}

toggle-ipv6() {
	# Microsoft/Azure workaround
	sleep 42s
	sysctl -w net.ipv6.conf."${IFLINK}".disable_ipv6=1 >/dev/null
	sleep 1s
	sysctl -w net.ipv6.conf."${IFLINK}".disable_ipv6=0 >/dev/null
}

[ -n "${MY_IFLINK}" ] || exit 0
[ -n "${MY_IPV6_SUFFIX}" ] || exit 0

IFLINK="$1"
NMMODE="$2"

case "${IFLINK}" in
"${MY_IFLINK}")
	case "${NMMODE}" in
	up)
		sleep 1s
		set-ipv6-token
		while ! ip a s "${IFLINK}" | grep ":${MY_IPV6_SUFFIX}/${PREFIX_LEN}"; do
			sleep 1s
			ip token del dev "${IFLINK}"
			set-ipv6-token
		done
		sleep 1s
		set-sysctl
		toggle-ipv6 &
		disown
	;;
	esac
;;
esac

exit 0
