## Version 2025/07/18
# make sure that your pihole container is named pihole
# make sure that your dns has a cname set for pihole

# https://nginx.org/en/docs/http/server_names.html

include /config/nginx/custom/quic-proxy.conf;

server {
    server_name ~^monitoring\..+\.keksgesicht\.de$;
    access_log /config/log/nginx/access-monitoring.log combined3;

    include /config/nginx/custom/8443.conf;
    include /config/nginx/custom/quic-internal.conf;

    location = / {
        return 302 https://$host/cmk/check_mk/;
    }

    location / {
        include /config/nginx/proxy.conf;
        proxy_pass http://127.0.0.1:5001/;
    }
}
