# https://nginx.org/en/docs/http/server_names.html

include /config/nginx/custom/quic-proxy.conf;

server {
    server_name ~^nix-serve\..+\.internal\.keksgesicht\.de$;
    access_log /config/log/nginx/access-nix-serve.log combined3;

    include /config/nginx/custom/8080.conf;

    location / {
        proxy_pass http://127.0.0.1:5000/;
        proxy_max_temp_file_size 2048m;
    }
}

server {
    server_name ~^nix-serve\..+\.internal\.keksgesicht\.de$;
    access_log /config/log/nginx/access-nix-serve.log combined3;

    include /config/nginx/custom/8443.conf;
    include /config/nginx/custom/quic-internal.conf;

    location / {
        include /config/nginx/proxy.conf;
        proxy_pass http://127.0.0.1:5000/;
        proxy_max_temp_file_size 2048m;
    }
}
