## Version 2025/07/18
# make sure that your pihole container is named pihole
# make sure that your dns has a cname set for pihole

# https://nginx.org/en/docs/http/server_names.html

include /config/nginx/custom/quic-proxy.conf;

server {
    server_name ~^pihole\..+\.keksgesicht\.de$;
    access_log /config/log/nginx/access-pihole.log combined3;

    include /config/nginx/custom/8443.conf;
    include /config/nginx/custom/quic-internal.conf;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        proxy_pass https://172.23.53.1:443/;
        proxy_hide_header X-Frame-Options;
    }
}
