# https://nginx.org/en/docs/http/server_names.html

server {
    include /config/nginx/custom/8080.conf;
    server_name nix-serve.cookieclicker.keksgesicht.de \
                nix-serve.cookieflyer.keksgesicht.de;

    location / {
        proxy_pass http://127.0.0.1:5000/;
        proxy_max_temp_file_size 2048m;
    }
}

server {
    include /config/nginx/custom/8443.conf;
    server_name nix-serve.cookieclicker.keksgesicht.de \
                nix-serve.cookieflyer.keksgesicht.de;

    location / {
        include /config/nginx/proxy.conf;
        proxy_pass http://127.0.0.1:5000/;
        proxy_max_temp_file_size 2048m;
    }
}
